
RADIO = '../data/Radiographs/'
EXTRA = '../data/Radiographs/extra/'
SEGMENT = '../data/Segmentations/'
FOUND = '../data/FoundSegmentations/'
RESULT = '../data/Combinations/'
CLAHE = '../data/CLAHE/'
HAT = '../data/HAT/'
SOBEL = '../data/Sobel/'
LANDMARK = '../data/Landmarks/original/'
